### ISSUE TITLE
Build on OSX

### ISSUE THREAD

**Issue by rumplestilzken** [jasonsantos/luajava#4]
It seems like the Makefile is not longer able to work on OSX 10.7.5.

I keep getting issues along the lines of :

In file included from src/c/luajava.c:39:
src/c/luajava.h:2:17: error: jni.h: No such file or directory

It seems that in the switch from Apple to Oracle, things have been moved.

**Comment by rodsenra** [comment]
I have successfully compiled it on Mac OSX, altering the following lines in...

Makefile:
$(SO_FILE): $(OBJS)
        export MACOSX_DEPLOYMENT_TARGET=10.11; $(CC) $(LIB_OPTION) -o $@ $? $(LIB_LUA)

 config:
INCS= -I$(JDK)/include -I$(JDK)/include/linux -I$(LUA_INCLUDES) -I$(JDK_HOME)/include -I$(JDK_HOME)/include/darwin
